---
geometry: top=0.85in, left=1in, footskip=0.85in
indent: true
eqnos-cleveref: On
fignos-cleveref: On
eqnos-plus-name: "Eq."
fignos-plus-name: "Fig."
number-sections: True
header-includes:
  \usepackage{microtype}
  \usepackage{mathpazo}
  \usepackage{palatino}
  \usepackage{sectsty}
  \usepackage{tikz}
  \usetikzlibrary{shapes.geometric, arrows}
  \sectionfont{\normalfont\sffamily}
  \subsectionfont{\normalfont\sffamily}
  \subsubsectionfont{\normalfont\sffamily\itshape}
  \linespread{1.5}
  \renewcommand{\thesection}{\Alph{section}}
  \usepackage{lineno}
  \linenumbers
---
